name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: carscout
          POSTGRES_PASSWORD: password
          POSTGRES_DB: carscout_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        ruff check .
    
    - name: Type check with mypy
      run: |
        mypy apps/ workers/ libs/ || true
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=apps --cov=workers --cov=libs
      env:
        DATABASE_URL: postgresql+asyncpg://carscout:password@localhost:5432/carscout_test
        DATABASE_SYNC_URL: postgresql://carscout:password@localhost:5432/carscout_test
        REDIS_URL: redis://localhost:6379/0
        CELERY_BROKER_URL: redis://localhost:6379/1
        CELERY_RESULT_BACKEND: redis://localhost:6379/2

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker images
      run: |
        docker build -f infra/docker/Dockerfile.api -t carscout-api:latest .
        docker build -f infra/docker/Dockerfile.bot -t carscout-bot:latest .
        docker build -f infra/docker/Dockerfile.worker -t carscout-worker:latest .
